pipeline {
    agent any

    stages {
        stage('Setup') {
            steps {
                git branch: 'main', url: 'https://github.com/lucaskschmitt/E2E-Test-OrderFlow'
            }
        }
        stage('Instalar Dependências') {
            steps{
               bat 'npm install' 
            }
        }
        stage('Subir servidor') {
            steps {
                bat 'start /b npm start'
                bat 'npx serverest'
            }
        }
        stage('Test') {
            steps {
               bat 'set NO_COLOR=1 npm run cy:run'
            }
        }
    }
}